### ISSUE TITLE
Not Able to fetch metrics from Elastic Cloud Cluster

### ISSUE THREAD

**Issue by infra-testuser** [prometheus-community/elasticsearch_exporter#1040]
I am not able to fetch the metrics from the elastic cloud cluster, have tried different approaches but none is working, is there anything which needs to be enabled or disabled in order to get the metrics.

docker-compose file:- 
```
version: '3.8'

services:
  elasticsearch_exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    command:
     - '--es.uri=https://es-cluster-testingXXXXXXX.kb.ap-south-1.aws.elastic-cloud.com'
    restart: always
    environment:
      - ES_API_KEY="XXXXXXXXXXXXXXXXHd3ZU0xZ1d4cHhpS1dJbTZxQQ=="
    ports:
    - "0.0.0.0:9114:9114"

networks:
  default:
````

Tried with :-

1. passing username and password in the environmental varibale (ES_PASSWORD and ES_USERNAME)
2. even in the url i have tried passing credentials.
3. then tried with api key as well.

Have anyone tried using this exporter to fetch metrics from elastic cloud.
