### ISSUE TITLE
[helm][es-exporter] Metrics are delayed with a single node ES cluster with low Prometheus scrape interval 

### ISSUE THREAD

**Issue by LaurentDumont** [prometheus-community/elasticsearch_exporter#466]
Hey everyone,

I'm trying to leverage the exporter to get some "real-time" statistics regarding our ELK cluster.

It's a singlenode and the usage is pretty low so I know that it's quick to answer (looking at the Dev tools for the request time for `/_nodes/stats` and `/_all/_stats` show that it takes about 100ms each to answer.

I've setup Prometheus to scrape the exporter every 10 seconds, thinking that it would let the metric refresh in between and I could get enough granularity.

But I can see that the retrieval metric is around 2 minutes still - using elasticsearch_clusterinfo_last_retrieval_success_ts (if it means what I think it does)

![image](https://user-images.githubusercontent.com/8936473/130064527-427b6a9f-f812-40ea-85e7-d5f7c69fabf9.png)

Prometheus config

```
- job_name: elasticsearch-exporter
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - URL_HERE:9108
```

I can see that Prometheus does scrape the exporter every 10 seconds in the Targets page of the server.

But if I look at the stats actually collected, it can take up to 20 minutes for the data to update (for metrics that I know should move faster)

Using `elasticsearch_indices_docs_total` for an indice that I know is actively receiving docs.

![image](https://user-images.githubusercontent.com/8936473/130065388-556478bd-ed13-4960-8de1-5a54737ab995.png)

Any ideas?
