### ISSUE TITLE
[Grafana] Dashboard not working

### ISSUE THREAD

**Issue by estebanramos** [prometheus-community/elasticsearch_exporter#467]
Hi, I've ran my container with 9114 port open and imported the grafana dashboard on the examples. I've defined my Prometheus datasource in Grafana using my url and port but the dashboard it's not showing any metrics.

**Comment by estebanramos** [comment]
Ok, now I have the metrics running but the cluster state it's still in N/A

**Comment by Fossil01** [comment]
I am enountering the same issue. 

```yaml
  elastic_exporter:
    container_name: elastic_exporter
    image: quay.io/prometheuscommunity/elasticsearch-exporter:master
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    command:
      - '--es.uri=http://elastic.redacted.tld'
      - '--es.all'
      - '--es.cluster_settings'
    depends_on:
      - prometheus
    ports:
      - "9114:9114"
    restart: unless-stopped
  ```

When browsing the metrics endpoint I am missing  alot of information. The dashboard for example looks for `elasticsearch_cluster_health_status` which does not exist. I am still running Elastic 7.9.0 though.
