### ISSUE TITLE
Exporter not fetching metrics from ES Cluster.

### ISSUE THREAD

**Issue by ashishkumar-vonage** [prometheus-community/elasticsearch_exporter#504]
Hello 

I am using docker-compose for exporters - 

```
services:

  # Prometheus Exporters ------------------------------
  elasticsearch-exporter-es1: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    image: 
    restart: always
    command: ["--es.uri", "https://${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}@${ELASTICSEARCH_HOST_ES1}:${ELASTICSEARCH_PORT}",
              "--es.all",
              "--es.ca", "/prod.pem",
              "--es.timeout", "900s",
              "--es.snapshots",
              "--es.indices"]
    ports:
      - "9114:9114"
```

**ELASTICSEARCH_PORT** - 9200

Logs of containers with above docker-compose as :
```
level=info ts=2021-11-24T09:16:18.202006334Z caller=clusterinfo.go:200 msg="triggering initial cluster info call"
level=info ts=2021-11-24T09:16:18.202160664Z caller=clusterinfo.go:169 msg="providing consumers with updated cluster info label"
level=info ts=2021-11-24T09:16:18.392123817Z caller=main.go:148 msg="started cluster info retriever" interval=5m0s
level=info ts=2021-11-24T09:16:18.392265145Z caller=main.go:188 msg="starting elasticsearch_exporter" addr=:9114
level=info ts=2021-11-24T09:21:18.205910718Z caller=clusterinfo.go:169 msg="providing consumers with updated cluster info label"
level=info ts=2021-11-24T09:26:18.20589678Z caller=clusterinfo.go:169 msg="providing consumers with updated cluster info label"
level=info ts=2021-11-24T09:31:18.205926061Z caller=clusterinfo.go:169 msg="providing consumers with updated cluster info label"
level=info ts=2021-11-24T09:36:18.205907181Z caller=clusterinfo.go:169 msg="providing consumers with updated cluster info label"
level=info ts=2021-11-24T09:41:18.205986891Z caller=clusterinfo.go:169 msg="providing consumers with updated cluster info label"
level=info ts=2021-11-24T09:46:18.205909305Z caller=clusterinfo.go:169 msg="providing consumers with updated cluster info label"
level=info ts=2021-11-24T09:51:18.205907934Z caller=clusterinfo.go:169 msg="providing consumers with updated cluster info label"

```
I am not getting any metrics of Elasticsearch or any metrics with labels -- elasticsearch_cluster_health_active_primary_shards, etc..

### As described in [https://github.com/prometheus-community/elasticsearch_exporter](https://github.com/prometheus-community/elasticsearch_exporter)- 
**es.all** -- by default is **False** 
**es.snapshots** -- by default is **False**

Now I am trying to make make above flags to **True**, but containers stopped saying "Invalid Argument 'True'".

```
services:

  # Prometheus Exporters ------------------------------
  elasticsearch-exporter-es1: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    image: 
    restart: always
    command: ["--es.uri", "https://${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}@${ELASTICSEARCH_HOST_ES1}:${ELASTICSEARCH_PORT}",
              "--es.all", "true"
              "--es.ca", "/prod.pem",
              "--es.timeout", "900s",
              "--es.snapshots", "true"
              "--es.indices", "true"]
    ports:
      - "9114:9114"
```
### The Prometheus Config file - 
```
# my global config
global:
  scrape_interval:     30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 25s # scrape_timeout is set to every 900s. The global default (10s).

    # Alertmanager configuration
    #alerting:
    #alertmanagers:
    #- static_configs:
    #- targets:
  # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any time series scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'elasticsearch-exporter-es1'
    static_configs:
      - targets: [ 'elasticsearch-exporter-es1:9114' ]
```

Please advise here, any help is highly appreciated.
