### ISSUE TITLE
Exporter high CPU utilization

### ISSUE THREAD

**Issue by ebuildy** [prometheus-community/elasticsearch_exporter#544]
Running this exporter on kubernetes, I see resources as usualy low for an exporter:

```
          requests:
            cpu: 10m
            memory: 80Mi
          limits:
            cpu: 100m
            memory: 128Mi
```

CPU graph is fine, but I see the container is throttled all the time. Digging CPU usage, I see small spikes when fetching metrics:

<img width="1435" alt="Capture d’écran 2022-03-10 à 20 02 45" src="https://user-images.githubusercontent.com/1219817/157736011-265d4af4-479c-404b-b31e-09622a1efd1d.png">

The ES cluster is quite small (3 nodes, a few indices), is it normal?
