### ISSUE TITLE
msg="failed to fetch and decode index stats" err="HTTP Request failed with code 403"

### ISSUE THREAD

**Issue by lynBIT** [prometheus-community/elasticsearch_exporter#647]
the config we're using:
/exporter-bin/elasticsearch_exporter/elasticsearch_exporter
--es.uri="${DOMAIN_ENDPOINT}"
--es.all
--es.indices
--es.indices_settings
--es.shards
--es.snapshots
--es.sslSkipVerify

When I used the 1.0.3 version, everything was fine, the above Settings were not changed, and when I upgraded to 1.4.0 or 1.5.0, however, error 403 was reported

**Comment by chburmeister** [comment]
Same issue on our side: 

Running in OpenShift, fetching from AWS' OpenSearch-service via aws-sigv4-proxy
```yaml
containers:
    - command:
        - elasticsearch_exporter
        - >-
          --es.uri=http://<sigv4-proxy>:9200
        - '--es.all'
        - '--es.cluster_settings'
        - '--es.timeout=60s'
        - '--es.indices'
        - '--es.indices_settings'
      image: 'quay.io/prometheuscommunity/elasticsearch-exporter:v1.5.0'
```
```bash
level=error ts=2022-11-16T09:26:17.807186556Z caller=indices.go:1126 err="HTTP Request failed with code 403"
level=warn ts=2022-11-16T09:26:17.807302385Z caller=indices.go:1207 msg="failed to fetch and decode index stats" err="HTTP Request failed with code 403"
```

Using 1.30 with no errors.
