### ISSUE TITLE
Passing elasticsearch password with special characters through environment variable

### ISSUE THREAD

**Issue by aolmosj** [prometheus-community/elasticsearch_exporter#673]
Hi,

I'm deploying this exporter in kubernetes with helm, and I'm setting this values.yaml to pass the elasticsearch credentials stored in a kubernetes secret.

```yaml
env:
  ES_URI: "https://$(ES_USERNAME):$(ES_PASSWORD)@elasticsearch-master:9200"

extraEnvSecrets:
  ES_PASSWORD:
    secret: elasticsearch-security-master-credentials
    key: password
  ES_USERNAME:
    secret: elasticsearch-security-master-credentials
    key: username
```

This works great with alphanumeric elasticsearch password, but when they have special characters, which is my case, I get this error:

```error
level=error caller=main.go:122 msg="failed to parse es.uri" err="parse \"https://elasticuser:XXXXXXXXXXq@elasticsearch-master:9200 \": invalid URL escape \"%8#\""
```

I can't find a way to url encode the password in this scenario. I don't think that the password should be stored url encoded in the secret, since it could be an issue for other pods using this secret. Any ideas?
