### ISSUE TITLE
The elasticsearch exporter cannot fetch metrics elasticsearch_process_cpu_percent

### ISSUE THREAD

**Issue by limboys** [prometheus-community/elasticsearch_exporter#704]
![image](https://user-images.githubusercontent.com/36941711/229425511-d793d115-f506-458e-bd07-139e34bb8c3d.png)

elasticseach cluster version elasticsearch-8.1.2
elasticseach-exporter  version  1.5.0
Configuration
```
        - name: exporter
          image: 'quay.io/prometheuscommunity/elasticsearch-exporter:v1.5.0'
          command:
            - elasticsearch_exporter
            - '--log.format=logfmt'
            - '--log.level=info'
            - '--es.uri=http://10.82.49.152:9200'
            - '--es.all'
            - '--es.indices'
            - '--es.indices_settings'
            - '--es.indices_mappings'
            - '--es.shards'
            - '--es.snapshots'
            - '--es.cluster_settings'
            - '--es.timeout=30s'
            - '--web.listen-address=:9108'
            - '--web.telemetry-path=/metrics'
          ports:
```
elasticsearch not use 'root' start,Whether other parameters need to be set?
