### ISSUE TITLE
Configuring Liveness/Readiness probes (httpGet -> scheme) is not working as expected through values file

### ISSUE THREAD

**Issue by mbasha86** [prometheus-community/elasticsearch_exporter#825]
Hi All,

We have configured elasticsearch_exporter to export metrics on HTTPS for Prometheus communication. This requires configuration for Liveness/Readiness probes to reflect that change in values.yaml file, so we had to change scheme to use for connecting to the host (HTTPS) as per below as an example:

```yaml
image:
  repository: quay.io/prometheuscommunity/elasticsearch-exporter
  tag: v1.6.0
  pullPolicy: IfNotPresent
  pullSecret: ""

podSecurityContext:
  runAsUser: 1000

livenessProbe:
  httpGet:
    scheme: HTTPS
readinessProbe:
  httpGet:
    scheme: HTTPS
.
.
.
```
However, we can see that this is not working as expected, as after deployment, i can see that scheme for Liveness/Readiness probes still use HTTP for deployed pod when it should not which cause crashing for this deployed pod. Would you please let us know if it is target state (exporter must not have probes) or it is a bug in helm chart (helm chart not have support for probes)?
