### ISSUE TITLE
The exporter is many times OOMKilled

### ISSUE THREAD

**Issue by LHozzan** [prometheus-community/elasticsearch_exporter#834]
Hello.

We discovered, that the exporter is many times OOMKilled. Here you can see many times memory peaks.
![Trial01](https://github.com/prometheus-community/elasticsearch_exporter/assets/24796361/8e334e02-e291-4884-9c01-a8a1d8e56eb2)

I have no clue, why sometimes the exporter need to use more RAM, but by default dont need it.

We have set this resources:
```yaml
resources:
  requests:
    cpu: 500m
    memory: 40Mi
  limits:
    cpu: 1500m
    memory: 60Mi
```

**Are there any memory leaks?**
