### ISSUE TITLE
elasticsearch exporter used too much memory ,is it normal

### ISSUE THREAD

**Issue by sunfloweryumi** [prometheus-community/elasticsearch_exporter#851]
version：elasticsearch_exporter-1.5.0.linux
config ：elasticsearch_exporter-1.5.0.linux/elasticsearch_exporter --es.all --es.indices --es.cluster_settings --es.indices_settings --es.shards --es.snapshots --es.timeout=10s --es.uri xxx
my question: elasticsearch_exporter used 4.5G resident memory and 5G memory, is it normal?

**Comment by pierreblais** [comment]
Hi, I asking myself the same question. I'm currently running `quay.io/prometheuscommunity/elasticsearch-exporter:v1.9.0` with:

```yaml
resources:
  requests:
    cpu: 1
    memory: 3Gi
  limits:
    memory: 3Gi
```

And it often crashloop-ing. Which operation may consume as much resource in this metrics exporter ?
